name: Daily Weather Notification

on:
  schedule:
    - cron: '0 22 * * *'  # UTC 时间 22:00 -> 北京时间 6:00
  workflow_dispatch:

jobs:
  weather-task:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install requests pypinyin schedule

      - name: Download previous temperature_record artifact
        uses: actions/download-artifact@v3
        with:
          name: temperature-record
          path: .

      - name: Run script
        run: python main.py

      - name: Upload updated temperature_record.json
        uses: actions/upload-artifact@v3
        with:
          name: temperature-record
          path: temperature_record.json
