name: Daily Weather Notification

on:
  schedule:
    - cron: '0 22 * * *'  # 每天北京时间早上6点运行
  workflow_dispatch:

jobs:
  weather-task:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install requests pypinyin schedule

      - name: Run weather script
        run: python main.py

      - name: Commit temperature record
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "github-actions"
          git add temperature_record.json
          git commit -m "Update temperature record" || echo "No changes to commit"
          git push
        env:
          # 这个令牌拥有写权限
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
